export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE';
export const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE';
export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const GET_EMPLOYEE = 'GET_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';

export const SIGN_IN = 'SING_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const REGISTRATION = 'REGISTRATION';
