export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE';
export const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE';
export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const GET_EMPLOYEE = 'GET_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';

export const SIGN_IN = 'SING_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const REGISTRATION = 'REGISTRATION';

export const FETCH_MEDICAL_PLANS = "FETCH_MEDICAL_PLANS";
export const ADD_PLAN = 'ADD_PLAN';
export const DELETE_PLAN = 'DELETE_PLAN';
export const FETCH_SELECTED_PLANS = "FETCH_SELECTED_PLANS";

export const FILTER_BY_METAL_TYPE = "FILTER_BY_METAL_TYPE";

