
export const CREATE_QUOTE = 'CREATE_QUOTE';
export const FIND_QUOTE = 'FIND_QUOTE';
export const GET_COMPANY = 'GET_COMPANY';
export const GET_QUOTE_PLANS = 'GET_QUOTE_PLANS';
export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE';
export const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE';
export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const GET_EMPLOYEE_STATISTIC = 'GET_EMPLOYEE_STATISTIC';
export const GET_EMPLOYEE = 'GET_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';

export const SIGN_IN = 'SING_IN';
export const PROFILE = 'PROFILE';
export const SIGN_OUT = 'SIGN_OUT';
export const REGISTRATION = 'REGISTRATION';

export const SAVE_UPDATE_COMPANY_PROFILE = 'SAVE_UPDATE_COMPANY_PROFILE';

export const FETCH_PLANS = "FETCH_PLANS";
export const GET_METAL_PLAN_STATISTIC = 'GET_METAL_PLAN_STATISTIC';
export const ADD_PLAN = 'ADD_PLAN';
export const DELETE_PLAN = 'DELETE_PLAN';

export const FILTER_PLANS_BY_METAL_TYPES = 'FILTER_PLANS_BY_METAL_TYPES';
export const SORT_PLANS_BY_MONTH_COST = 'SORT_PLANS_BY_MONTH_COST';

export const FETCH_SELECTED_PLANS = "FETCH_SELECTED_PLANS";

export const GET_QUOTE_STATISTIC = 'GET_QUOTE_STATISTIC';

